<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="nikivm">
        <title>VPS management - installation</title>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
        <link rel="shortcut icon" href="img/favicon.png">
        <link href="css/materialize.min.css" rel="stylesheet">
        <link href="css/style.css" rel="stylesheet">
        <script src="css/jquery.js"></script>
        <script src="css/materialize.min.js"></script>
    </head>
    <body>
        <nav class="light-blue darken-1">
            <div class="nav-wrapper center-align">
                <a href="/web/index.php/site" class="navbar-brand"><img src="img/logo.png"></a>
            </div>
        </nav>

        <div class="fixed-action-btn">
            <a class="btn-floating btn-large amber hoverable" onclick="reloadPage()">
                <i class="large material-icons">refresh</i>
            </a>
        </div>
        <div class="content">
            <div class="row">